# Site settings
title: Technical Blog
email: g-dev@zigexn.vn
contact: > # this means to ignore newlines until "baseurl:"
 <b>Thông tin liên hệ:</b> Lầu 4, MIRAE BUSINESS CENTER 268 Tô Hiến Thành, Phường 15 Quận 10, Tp. Hồ Chí Minh, Việt Nam.<br><i>Phone:</i> (84)-838-633-399 - <i>Email:</i> <a href='mailto:info@zigexn.vn'>info@zigexn.vn</a>
description: "Technical Blog nơi hội tụ tất cả bài viết về công nghệ được đúc kết lại từ kinh nghiệm làm việc, sự tìm tòi, nghiên cứu của những kỹ sư trẻ tại ZIGExN VeNtura,nơi mà các VeNers có thể thỏa sức đam mê của mình sáng tạo cùng công nghệ, học hỏi và chia sẻ kinh nghiệm IT với tất cả mọi người."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tech.zigexn.vn" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
facebook_username: ZigexnVenturaCoLtd
website: zigexn.vn
# Build settings
markdown: kramdown
link_recruitment: "http://recruitment.zigexn.vn/#recuiment-section"
RoR: [N+1 problem, Rails concern,Arel, Rails API, Bang Method, Debug, How to use S3, Rubocop, Translated content]
WebDev: [Design pattern, Refactaring series, JS Topic, Solr, Lucene, Scrum]
Infrastructure: [Docker, Zabix, Capistrano, How to use nginx, Unicorn, Apache]
paginate: 6
paginate_path: "/page/:num"
permalink: /:categories/:year/:title
gems:
  - jekyll-sitemap