# Site settings
title: Technical Blog
email: g-dev@zigexn.vn
description: > # this means to ignore newlines until "baseurl:"
 <b>Thông tin liên hệ:</b> Lầu 4, MIRAE BUSINESS CENTER 268 Tô Hiến Thành, Phường 15 Quận 10, Tp. Hồ Chí Minh, Việt Nam.<br><i>Phone:</i> (84)-838-633-399 - <i>Email:</i> <a href='mailto:info@zigexn.vn'>info@zigexn.vn</a>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "zigexn-ventura.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
facebook_username: ZigexnVenturaCoLtd
website: zigexn.vn
# Build settings
markdown: kramdown
link_recruitment: "http://recruitment.zigexn.vn/#recuiment-section"
RoR: [N+1 problem, Rails concern,Arel, Rails API, Bang Method, Debug, How to use S3, Rubocop, Translated content]
WebDev: [Design pattern, Refactaring series, JS Topic, Solr, Lucene, Scrum]
Infrastructure: [Docker, Zabix, Capistrano, How to use nginx, Unicorn, Apache]
paginate: 6
paginate_path: "/page/:num"
permalink: /:categories/:year/:title