# Site
name: Zigexn VeNtura Technical Blog
title: Zigexn VeNtura Technical Blog
description: > # this means to ignore newlines until "baseurl:"
 <b>Thông tin liên hệ:</b> Lầu 4, MIRAE BUSINESS CENTER 268 Tô Hiến Thành, Phường 15 Quận 10, Tp. Hồ Chí Minh, Việt Nam.<br><i>Phone:</i> (84)-838-633-399 - <i>Email:</i> <a href='mailto:info@zigexn.vn'>info@zigexn.vn</a>
meta_description: Zigexn VeNtura Technical Blog
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: ""
email: wowthemesnet@gmail.com
google_analytics: "" #UA-46278016-1
disqus: ""
sharethis: "" # <script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'
permalink: /:title/
twitter_username: jekyllrb
github_username:  jekyll
facebook_username: ZigexnVenturaCoLtd
website: zigexn.vn
google_analytics: UA-38031325-11

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Build settings
markdown: kramdown
highlighter: rouge
link_recruitment: "http://recruitment.zigexn.vn/#recuiment-section"
RoR: [N+1 problem, Rails concern,Arel, Rails API, Bang Method, Debug, How to use S3, Rubocop, Translated content]
WebDev: [Design pattern, Refactaring series, JS Topic, Solr, Lucene, Scrum]
Infrastructure: [Docker, Zabix, Capistrano, How to use nginx, Unicorn, Apache]
paginate: 6
paginate_path: "/page/:num"


# Authors
authors:
  Vinh Nguyen:
    name: Vinh Nguyen
    url: https://github.com/vinh-nguyen
    img: https://avatars0.githubusercontent.com/u/5134525?v=4
  Son Dang:
    name: Son Dang
    url: https://github.com/ghost
    img: https://avatars0.githubusercontent.com/u/10137?v=4
  Trong Huu:
    name: Trong Huu
    url: https://github.com/huujapan
    img: https://avatars0.githubusercontent.com/u/20272961?v=4
  Vy Dao:
    name: Vy Dao
    url: https://github.com/vydn
    img: https://avatars1.githubusercontent.com/u/12061401?v=4
  Huy Binh:
    name: Huy Binh
    url: https://github.com/brianfw
    img: https://avatars1.githubusercontent.com/u/12490674?v=4
  Thao Phan:
    name: Thao Phan
    url: https://github.com/thaozigexn
    img: https://avatars1.githubusercontent.com/u/13670757?v=4
  KhieuLQ:
    name: KhieuLQ
    url: https://github.com/KhieuLe
    img: https://avatars0.githubusercontent.com/u/10445458?v=4
  ThaoNNM:
    name: ThaoNNM
    url: https://github.com/thaonnm
    img: https://avatars1.githubusercontent.com/u/14268417?v=4
  Lân Nguyễn:
    name: Lân Nguyễn
    url: https://github.com/lannn
    img: https://avatars3.githubusercontent.com/u/4487532?v=4
  Kiet Nguyen:
    name: Kiet Nguyen
    url: https://github.com/kietnvt
    img: https://avatars1.githubusercontent.com/u/10217063?v=4


